### ISSUE TITLE
Trying to connect to a camera crashes the app

### ISSUE THREAD

**Issue by samtun** [nabto/edge-android-webrtc#1]
Preconditions:
* The WebRTC Quick Demo container is running and the device is connected to the account
![Screenshot 2024-08-21 at 09 27 19](https://github.com/user-attachments/assets/90e10c8a-cd68-4b1f-a59c-f37a780e38e9)
* The same account is logged in in the app

How to reproduce:
* Start the app and tap any camera device

Expected behaviour:
* Camera stream is shown, no crash

Actual bevaiour:
* App crashes with this error:
```
FATAL EXCEPTION: DefaultDispatcher-worker-4
Process: com.nabto.edge.webrtcdemo, PID: 1463
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "iceServers" (class com.nabto.edge.client.webrtc.SignalMessage), not marked as ignorable (4 known properties: "servers", "type", "metadata", "data"])
	at [Source: (String)"{"iceServers":[{"credential":"0Q3N1O2vBwba2zcoc6dZ7LBs2+E=","urls":["turn:global.turn.nabto.net?transport=udp"],"username":"1724311350:pr-swykioh3:de-9ddqxutm:foobar"},{"urls":["stun:stun.nabto.net:3478"]}],"servers":[{"hostname":"turn:global.turn.nabto.net?transport=udp","password":"0Q3N1O2vBwba2zcoc6dZ7LBs2+E=","port":0,"username":"1724311350:pr-swykioh3:de-9ddqxutm:foobar"},{"hostname":"stun:stun.nabto.net:3478","password":"","port":0,"username":""}],"type":4}"; line: 1, column: 468] (through reference chain: com.nabto.edge.client.webrtc.SignalMessage["iceServers"])
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2036)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1650)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:540)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.nabto.edge.client.webrtc.impl.EdgeStreamSignaling.recv(EdgeStreamSignaling.kt:95)
	at com.nabto.edge.client.webrtc.impl.EdgeStreamSignaling$recv$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2eb23dd, Dispatchers.IO]
```

This also happens when I use the app directly from the Google play store.
Maybe I am also missing something? But from the documentation I don't see anything that could be the cause.
___

BTW: Building the app failed initially, because of gradle/java issues. I had to do some gradle upgrades to get it running. It might be a good idea to update the repo.

**Comment by samtun** [comment]
Thanks for the swift work. The app does not crash anymore.
However I still get an error in the app when opening the camera:

<img width="510" alt="Screenshot 2024-08-21 at 15 49 48" src="https://github.com/user-attachments/assets/a7b228cd-894e-4ae7-a38d-00d098b82def">

```
FATAL EXCEPTION: main
Process: com.nabto.edge.webrtcdemo, PID: 5803
com.nabto.edge.client.NabtoRuntimeException: Stopped
	at com.nabto.edge.client.ktx.ExtensionsKt$nabtoCoroutineWrapper$2$callback$1.invoke(extensions.kt:17)
	at com.nabto.edge.client.ktx.ExtensionsKt$nabtoCoroutineWrapper$2$callback$1.invoke(extensions.kt:9)
	at com.nabto.edge.client.ktx.ExtensionsKt$sam$com_nabto_edge_client_NabtoCallback$0.run(Unknown Source:6)
	at com.nabto.edge.client.impl.Util$1.run(Util.java:29)
	at com.nabto.edge.client.swig.NabtoClientJNI.SwigDirector_FutureCallback_run(NabtoClientJNI.java:172)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5b78bea, Dispatchers.Main.immediate]
Caused by: com.nabto.edge.client.swig.NabtoException: Stopped
	at com.nabto.edge.client.ktx.ExtensionsKt$nabtoCoroutineWrapper$2$callback$1.invoke(extensions.kt:13)
	... 4 more
```

After that another error message follows, which I am not sure if it is related:
Setting remote SDP failed: Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='device-0'.

I already tried deleting the device in my account and creating a new one, but the result is the same.

**Comment by gammelby** [comment]
Streaming H264 [is not supported](https://docs.nabto.com/developer/platforms/android/webrtc.html#:~:text=Note%20that%20the%20Nabto%20Edge%20WebRTC%20Video%20app%20currently%20must%20be%20run%20on%20a%20physical%20Android%20device%20if%20streaming%20an%20H264%20feed%20(the%20demo%20video%20device%20does%20that).) in the emulator, unfortunately. I admit that the demo's error message is not ideal in this regard - we will improve that. 

The exception you pasted seems to be caused by the demo accidentally using a stopped resource and then in turn not gracefully handling the resulting error. A stopped resource could e.g. be a CoAP request, a connection or the client context itself. That is, some logic error in the demo. We will also look into that. If you can provide some additional info about how to reproduce, it would be helpful!

**Comment by samtun** [comment]
The emulator part was the only information I was missing. I think I read it somewhere in the docs too but forgot about it when quickly retesting yesterday.

Retested on a real Pixel 6a: It's alive! Thank you so much :)
![Screenshot 2024-08-22 at 10 51 52](https://github.com/user-attachments/assets/1a270cd1-658f-4840-9b93-5afcee8456e6)
